### ISSUE TITLE
BothMatchFunc expects a bool as return value

### ISSUE THREAD

**Issue by frefardt** [etlbox/etlbox#77]
Hi Andreas

I am using MergeJoin and the ComparisonFunction (named BothMatchFunc). As I understand from the description and also the current code it expects an int as return value. But currently it asks me for a bool. Can you explain why?

```
mergeJoin.BothMatchFunc = (leftRow, rightRow) =>
            {
                return true;
            };

```

I am on version 2.1.1.

Regards Florian

**Comment by andreaslennartz** [comment]
Hi @frefardt ,

sorry for the inconvenience. Version 2.1.1 does not properly implement the functionality to match records in the MergeJoin.

Please upgrade to version 2.1.2. Tje initial idea of a BothMatchFunc didn't really work out. The MergeJoin needs Comparison function if you don't want to join always both records. 
I updated the documentation describing the MergeJoin a lot, it should give you more insights how  to use it: https://etlbox.net/articles/transformations/broadcast_merge_join.html#join-with-comparison

Also, you will find some example code in issue #73 .

**Comment by frefardt** [comment]
Hi @andreaslennartz 

I just upgraded to version 2.1.1. After a quick fix for the ComparisonFunc for the MergeJoin my code compiled and run.  I will have a more detailed look into the new documentation tomorrow. Thanks for your work, it's very much apprechiated!

regards Florian

**Comment by andreaslennartz** [comment]
Hi @frefardt ,

I assume this is working for you now? I will close this issue then, feel free to reopen if things don't work as expected.
