### ISSUE TITLE
How to support low version database, such as SQL Server 2005 2008

### ISSUE THREAD

**Issue by bxjg1987** [etlbox/etlbox#79]
By default (non customsource) sqlserver2008 Oracle11g is not supported in current tests, and SQL statements must be written manually

**Comment by andreaslennartz** [comment]
Hi @bxjg1987 ,

Microsoft and Oracle do define main and extended support periods for their database products. 
Sql Server 2005 & 2008 and Oracle 11g  are out of main support and also out of extended support. 
ETLBox does only support databases that are still in main support. Of course many features of ETLBox will also work with older versions, as databases vendors always try to stay backward compatible.  
But I can't offer any support for databases that are already out of extended support.

**Comment by andreaslennartz** [comment]
If you are in need of a custom-made solution with support for older databases, you can request an offer via mail@etlbox.net

**Comment by bxjg1987** [comment]
@andreaslennartz Thank you very much！I'm learning and testing etlbox。
