### ISSUE TITLE
Question:Multi  transform

### ISSUE THREAD

**Issue by Qlimax2009** [etlbox/etlbox#82]
I want to divide a table into two. 
```
var connMan = new  MySqlConnectionManager("Server=localhost;Database=TestDb1;User Id=root; Port=3308; Password=111111;connect timeout=120;");
            DbSource<OldBook> source = new DbSource<OldBook>()
            {
                ConnectionManager = connMan,
                Sql = "SELECT id, name, price FROM book"
            };
            var connMan2 = new MySqlConnectionManager("Server=localhost;Database=TestDb2;User Id=root; Port=3308; Password=111111;connect timeout=120;");
            DbDestination<NewBookPrice> dest1 = new DbDestination<NewBookPrice>(connMan2, "bookprice");
            DbDestination<NewBook> dest2 = new DbDestination<NewBook>(connMan2, "book");

            var rowTrans1 = new RowTransformation<OldBook, NewBookPrice>();
            rowTrans1.TransformationFunc =
                row =>
                {
                    return new NewBookPrice()
                    {
                        id = row.id,
                        importprice = null,
                        sellprice = row.price,
                    };
                };

            var rowTrans2 = new RowTransformation<OldBook, NewBook>();
            rowTrans2.TransformationFunc =
                row =>
                {
                    return new NewBook()
                    {
                        id = row.id,
                        name = row.name,
                        shelfId = row.id,
                    };
                };

            source.LinkTo<NewBookPrice>(rowTrans1).LinkTo(dest1);
            source.LinkTo<NewBook>(rowTrans2).LinkTo(dest2);
            source.Execute();
            dest1.Wait();
            dest2.Wait();
```

When I ran this,`rowTrans1 ` worked, but `rowTrans2` did not work.
Is this a bug? or there is a another way to reach my goal.
Thank in advance.

**Comment by andreaslennartz** [comment]
Hi @Qlimax2009 ,

thanks for using ETLBox. 
This is actually not a bug, but the expected behavior by design. ETLBox can't tell by the code if you want to broadcast or split your data. If a source is linked to multiple targets without any predicates, all data is send to the first target that was linked to source. To duplicate your data, you simply need to add a Multicast directly after your source. 

I tried to cover the difference between broadcasting and splitting the data here: https://etlbox.net/articles/transformations/broadcast_merge_join.html

But I must admit that the default behavior can be confusing at first glance. I guess some logging output during execution could be helpful. 

So, if you modify your code like this, it should work as you expect:

```
var connMan = new  MySqlConnectionManager("Server=localhost;Database=TestDb1;User Id=root; Port=3308; Password=111111;connect timeout=120;");
            DbSource<OldBook> source = new DbSource<OldBook>()
            {
                ConnectionManager = connMan,
                Sql = "SELECT id, name, price FROM book"
            };
            var connMan2 = new MySqlConnectionManager("Server=localhost;Database=TestDb2;User Id=root; Port=3308; Password=111111;connect timeout=120;");
            DbDestination<NewBookPrice> dest1 = new DbDestination<NewBookPrice>(connMan2, "bookprice");
            DbDestination<NewBook> dest2 = new DbDestination<NewBook>(connMan2, "book");

            var rowTrans1 = new RowTransformation<OldBook, NewBookPrice>();
            rowTrans1.TransformationFunc =
                row =>
                {
                    return new NewBookPrice()
                    {
                        id = row.id,
                        importprice = null,
                        sellprice = row.price,
                    };
                };

            var rowTrans2 = new RowTransformation<OldBook, NewBook>();
            rowTrans2.TransformationFunc =
                row =>
                {
                    return new NewBook()
                    {
                        id = row.id,
                        name = row.name,
                        shelfId = row.id,
                    };
                };

            var multicast = new Multicast<OldBook>();
            source.LinkTo(multicast);
            multicast.LinkTo<NewBookPrice>(rowTrans1).LinkTo(dest1);
            multicast.LinkTo<NewBook>(rowTrans2).LinkTo(dest2);

            source.Execute();
            dest1.Wait();
            dest2.Wait();
```

**Comment by Qlimax2009** [comment]
> Hi @Qlimax2009 ,
> 
> thanks for using ETLBox.
> This is actually not a bug, but the expected behavior by design. ETLBox can't tell by the code if you want to broadcast or split your data. If a source is linked to multiple targets without any predicates, all data is send to the first target that was linked to source. To duplicate your data, you simply need to add a Multicast directly after your source.
> 
> I tried to cover the difference between broadcasting and splitting the data here: https://etlbox.net/articles/transformations/broadcast_merge_join.html
> 
> But I must admit that the default behavior can be confusing at first glance. I guess some logging output during execution could be helpful.
> 
> So, if you modify your code like this, it should work as you expect:
> 
> ```
> ...
>             var multicast = new Multicast<OldBook>();
>             source.LinkTo(multicast);
>             multicast.LinkTo<NewBookPrice>(rowTrans1).LinkTo(dest1);
>             multicast.LinkTo<NewBook>(rowTrans2).LinkTo(dest2);
> 
>             source.Execute();
>             dest1.Wait();
>             dest2.Wait();
> ```

Thank you for your reply. 
It works.
I read it before, but I didn't look at it carefully. That's my fault.
Thanks again.
