### ISSUE TITLE
Error in function BulkInsertData

### ISSUE THREAD

**Issue by Qlimax2009** [etlbox/etlbox#83]
When ran a simple transform, It throws "Object must implement IConvertible".
I think it may caused by 'byte[]', When I try to transform a entity with 'byte[]' field, it happened.

**Comment by andreaslennartz** [comment]
Hi @Qlimax2009 ,

Thanks for reporting this bug. I will try to reproduce this in my test environment.

A quick question about this; Are you using the DbDestination to write data into the database? could you tell me which  database you are using and what kind of data type the target column had you wanted to write the byte[] data into?

**Comment by Qlimax2009** [comment]
> Hi @Qlimax2009 ,
> 
> Thanks for reporting this bug. I will try to reproduce this in my test environment.
> 
> A quick question about this; Are you using the DbDestination to write data into the database? could you tell me which database you are using and what kind of data type the target column had you wanted to write the byte[] data into?

Thank you for your reply. I uesed the DbDestination to save data to postgre. The data type is bytea in postgre, and I used efcore to create the entity.

**Comment by andreaslennartz** [comment]
Thanks for the details, that helped me to reproduce the issue. I was able to fix this, the next version will contain the fix. Probably I will do a release in the next couple of days, I'll keep you updated.

**Comment by andreaslennartz** [comment]
Hi @Qlimax2009 ,

I just released version 2.2.3 (https://www.nuget.org/packages/ETLBox/2.2.3) which should now work smoothly with binary data and postgres. You should now be able to write a `byte[]` into a `bytea` column in Postgres.
Let me know if you encounter any issus!
