### ISSUE TITLE
Error with timespan in Postgres

### ISSUE THREAD

**Issue by Qlimax2009** [etlbox/etlbox#84]
The etlbox can not write `timespan ` into a `interval ` column in Postgres.

**Comment by andreaslennartz** [comment]
Hi,
thanks for reporting this bug. I was able to reproduce and fix it already. The fix will be part of the next version (likely 2.3.0). I will keep you updated when I release it.

**Comment by Qlimax2009** [comment]
I read some source code, why not separate the database operation(like `DataTypeConverter`,`BulkSqlGenerator`) from the project.  Modular design is easier to develop and maintain.Of course, this is just a suggestion.

**Comment by andreaslennartz** [comment]
Hi @Qlimax2009 ,
thanks for your feedback. I am not quite sure if I fully understand your suggestion. What is a module for you? Are you thinking of a cleaner separation of the classes itself, or are you thinking of a different project? Database operations do sound a little bit like like "all-or-nothing" to me, could you describe a little bit more what you would put into this?

**Comment by andreaslennartz** [comment]
HI @Qlimax2009 ,

just released version 2.3.0 (https://www.nuget.org/packages/ETLBox/2.3.0)
This will support to write timespan (clr type) into a postgres interval (db type).
