### ISSUE TITLE
API Documentation on Website partly missing

### ISSUE THREAD

**Issue by frefardt** [etlbox/etlbox#85]
Under https://etlbox.net/api/ETLBox.DataFlow.html all the description for the connectors are missing. Can you please check and re-generate the API Documentation if needed.

Thanks and regards Florian

**Comment by andreaslennartz** [comment]
Hi @frefardt ,

thanks for letting me know. I fixed the bug and regenerated the API documentation, it should now be complete again. 
Thanks!
