### ISSUE TITLE
Q: How to override the identity column (SET IDENTITY_INSERT ON) ?

### ISSUE THREAD

**Issue by jalchr** [etlbox/etlbox#90]
Hi,
In Sql Server there is a way to override the identity column (SET IDENTITY_INSERT ON). 
How to use this with DbMerge or DbDestination ?

I need to insert values into the identity column. 
Please advise !

**Comment by andreaslennartz** [comment]
Hi @jalchr ,

Thanks for using ETLBox.

The DbDestination has a property `KeepIdentity` - simply set it to true and the identity values should preserved when you insert data.

For the DBMerge this is not necessary. It should automatically detect if you are including an identity column.

I must admit that the documentation misses some details here.

Let me know if this solves your issue!

**Comment by andreaslennartz** [comment]
Hi @jalchr ,

Thanks for using ETLBox.

The DbDestination has a property KeepIdentity - simply set it to true and the identity values should preserved when you insert data.

For the DBMerge this is not necessary. It should automatically detect if you are including an identity column.

I must admit that the documentation misses some details here.

Let me know if this solves your issue!

**Comment by jalchr** [comment]
Hi @andreaslennartz, amazing library !

Your tip should solved this issue. Yes, it would be awesome to have such info in the documentation or may be renamed to "AllowIdentityInserts" is more self-explanatory

**Comment by andreaslennartz** [comment]
Thanks for the feedback! Extending the documentation is added to my list, and I will review the naming of the property for the next version. AllowIdentityInsert as new name is a very good suggestion.

**Comment by andreaslennartz** [comment]
I renamed the property based on your suggestion (starting with 2.4.4)
Documentation update will follow. Thanks for your feedback!
