### ISSUE TITLE
Logging of Load Processes breaks in 2.5.1

### ISSUE THREAD

**Issue by frefardt** [etlbox/etlbox#92]
Hi Andreas

When I update from 2.4.4 to 2.5.1 the logging part in my code breaks. The following classes are not known:

- StartLoadProcessTask
- AbortLoadProcessTask
- EndLoadProcessTask

For example in my code this would not compile anymore.

> 
> **StartLoadProcessTask**.Start($"{this.GetType().Name}.ProcessComponent", $"Start processing ProcessComponent");
>                 try
>                 {
>                     Network.Execute(sourceConnector);
>                     ...
>                 }
>                 catch (Exception e)
>                 {
>                     LogTask.Error("An Error occured during ProcessComponent part NetworkExecute");
>                     **AbortLoadProcessTask**.Abort(e.ToString());
>                    ...
>                 }
>                 finally
>                 {
>                     **EndLoadProcessTask**.End("The process ProcessComponent part NetworkExecute ended successfully");
>                 }

Did you change this part? Do I have to change my code?

Regards Florian

**Comment by andreaslennartz** [comment]
Hi @frefardt ,

thanks for reporting this.
There were "breaking changes" regarding logging introduced in version 2.5.0:  (see also https://www.etlbox.net/support/release-notes/)

- DataFlow.LoggingThresholdRows renamed to LogThreshold
- Combining CreateLogTable and ReadLogTable tasks into LogTask (e.g. use LogTask.CreateLogTable(..) instead)
- Introducing structured logging - core package now supports general ILogger interface instead NLog. You can now assign your ILogger instance to the static property Logging.LogInstance. Now NLog, Serilog and other logger supporting the log abstraction interface will be supported.

With version 2.5.0 I switched from NLog to the Microsoft.Extensions.Logging abstraction. That means that you are not forced to use Nlog anymore - any log provider that supports the Microsoft Logging API will now work (e.g. Serilog). Also, I switched to "structured logging messages" to have better support for log analysis tools like Kibana. 

Please note that the nlog.config differs a little bit between 2.4.4 and 2.5.0. In 2.5.0 you need to use the MLDC layout renderers instead, they are replacing the custom etllog layout renderers. Also, you will need to add a reference to NLog in your project, and create a log instance. 

The logging documentation should be updated to reflect these changes: https://www.etlbox.net/docs/control-flow/logging/

Let me know if you encounter any wrong informations or flaws with the udpated docs, or if you have issues to get your logging up & running again.

**Comment by frefardt** [comment]
Hi @andreaslennartz 

Thanks for your reply. This is very helpful.
I will be working on the logging part next week and migrate my solution to 2.5.1. An update of the documentation would be helpful of course :-). If I run in any sort of trouble during my changes I will let you know of course.

Regards Florian

**Comment by andreaslennartz** [comment]
Sure, just let me know if you need support.
The documentation is already updated, let me know if you find any flaws (the website is now also in a public repository: https://github.com/etlbox/etlbox.website
